/**
 * Loads site-data.json (generated by CI) and fills dynamic install/release UI.
 */
(async function () {
  const $ = (sel) => document.querySelector(sel);
  const $$ = (sel) => [...document.querySelectorAll(sel)];

  let data;
  try {
    const res = await fetch("site-data.json", { cache: "no-store" });
    if (!res.ok) throw new Error(res.statusText);
    data = await res.json();
  } catch {
    data = null;
  }

  if (!data) return;

  const setText = (sel, text) => {
    $$(sel).forEach((el) => { el.textContent = text; });
  };
  const setHref = (sel, href) => {
    $$(sel).forEach((el) => { el.href = href; });
  };

  setText("[data-version]", data.version);
  setText("[data-package-version]", data.packageVersion);
  setText("[data-extension-id]", data.extensionId);
  setText("[data-ovsx-version]", data.ovsx.version ?? "—");
  setText("[data-github-tag]", data.github.releaseTag);
  setText("[data-vsix-name]", data.github.vsixName);
  setText("[data-generated]", new Date(data.generatedAt).toLocaleString());

  setHref("[data-href-ovsx]", data.ovsx.url);
  setHref("[data-href-release]", data.github.releaseUrl);
  setHref("[data-href-vsix]", data.github.vsixUrl);
  setHref("[data-href-repo]", data.repository);

  const cmd = (id, text) => {
    const el = document.getElementById(id);
    if (el) el.textContent = text;
  };
  cmd("cmd-vsix", data.install.vsixCommand);
  cmd("cmd-release-patch", data.install.releasePatch);
  cmd("cmd-release-minor", data.install.releaseMinor);
  cmd("cmd-ovsx-search", data.install.ovsxSearch);

  const ovsxBadge = $("#ovsx-status");
  if (ovsxBadge && data.ovsx.version) {
    ovsxBadge.textContent = data.ovsx.downloadable
      ? `Open VSX v${data.ovsx.version} · live`
      : `Open VSX v${data.ovsx.version} · syncing`;
    ovsxBadge.classList.add(data.ovsx.downloadable ? "live" : "pending");
  }

  const metaOg = document.querySelector('meta[property="og:image"]');
  if (metaOg) {
    metaOg.setAttribute("content", new URL("assets/marketing/og-social-card.png", window.location.href).href);
  }

  document.title = `${data.displayName} v${data.version} — Live Cursor Usage Dashboard`;
})();
